### PR TITLE
[11.0] [MIG] l10n_ro_partner_create_by_vat

### PR DESCRIPTION
**Pull request by feketemihai**
Migrate module l10n_ro_partner_create_by_vat, keep history from v 8.0.

### CODE REVIEW

**Comment by feketemihai** [comment]
Error in codecov patch...travis and runbot is ok.

**Comment by feketemihai** [comment]
@OCA/core-maintainers Can someone review this, please?

**Review by moylop260 — APPROVED** [review]
The code could be better in some cases but I don't like to blocked it.
👍 (optimistic merge)

**Review by dreispt — APPROVED** [review]
LGTM

**Comment by feketemihai** [comment]
@dreispt Thanks for the merge...there are a lot of PR's, but since people from Romania don't want to contribute, they remain a lot of time not merged...
Thanks again @dreispt and @moylop260 for taking time to review.

**Pull request merged**
