### PR TITLE
Update travis, add transifex, add oca_dependencies...

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by feketemihai** [comment]
I don't have a clue why coverage is still pending...probably since there is no code on the repo?

**Comment by pedrobaeza** [comment]
There was a fail in Coveralls that leads to that. Ignore it.

**Comment by pedrobaeza** [comment]
Please sign the CLA and I'll merge.

**Comment by feketemihai** [comment]
@pedrobaeza I already sign it, but at first commit i used a different config in git user.email...and at last commit i already changed it to the right one.

**Comment by pedrobaeza** [comment]
OK, thanks. Can you make one little thing more? Please squash your commits in one as this is a basic PR that doesn't need to store all the commit history.

**Comment by feketemihai** [comment]
@pedrobaeza @max3903 I created another PR, since i didn't succes to squash the commits. Please see #3.

**Pull request closed without merging**
