### PR TITLE
[17.0][MIG] currency_rate_update_RO_BNR: Migration to 17.0

### PR DESCRIPTION
**Pull request by razvanioan**
What has been changed:

1. migrated to 17.0 following OCA guidelines
2. removed unnecessary `inverse_rate` field from `res.currency.rate` *model* and *views* as there is a default one in Odoo base `company_inverse_rate`
3. update `i18n/currency_rate_update_RO_BNR.pot` translation template file
4. update tests to match v17 and pass

### CODE REVIEW

**Comment by feketemihai** [comment]
@razvanioan Salut, felicitari penrtu contributie, dar te rog cumva daca faci pr sa le faci in ordinea dependintelor, adica priam data l10n_ro_config...si de acolo restul.

**Comment by razvanioan** [comment]
@feketemihai absolut voi face așa, dar cel cu BNR nu depinde de restul modulelor din acest repository
Urmează l10n_ro_config, și altele la care am mai lucrat eu

**Comment by feketemihai** [comment]
Salut, am verificat un pic, se pare ca in 16 nu mai are direcotrul de readme, te rog daca se poate sa il adaugi din 15 https://github.com/OCA/l10n-romania/tree/15.0/l10n_ro_account_edit_currency_rate/readme si sa te pui si pe tine la sectiunea de contributors.

**Comment by razvanioan** [comment]
done

**Comment by razvanioan** [comment]
Salut @feketemihai,

Nu înțeleg eroarea.
De ce apare numele modulului `odoo-addon-....` ?
Cum pot rezolva ?

**Comment by feketemihai** [comment]
Salut, nu stiu, e ceva din wheel cand face pachetul pentru linux...o sa verific daca se schimba ceva in maintainer-tools sau https://github.com/sbidoul/whool

**Comment by feketemihai** [comment]
@sbidoul Do you know exactly what is the issue with this PR, we got an error in the build wheel creation?

**Comment by sbidoul** [comment]
@feketemihai you are hitting https://github.com/acsone/manifestoo-core/issues/63. I'll fix soon.

**Comment by sbidoul** [comment]
@feketemihai please retry.

**Comment by feketemihai** [comment]
> @feketemihai please retry.

@sbidoul Thanks for your support and quick reaction. Happy Holidays.

**Comment by sbidoul** [comment]
Happy Holidays to you too :)

**Pull request merged**
