### PR TITLE
[13.0] [MIG] l10n_ro_vat_on_payment

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by cvinh** [comment]
@feketemihai about vat on payment, do you think that this module is still useful considering 'tax on cash basis' approach in odoo v13 ?
https://www.odoo.com/documentation/user/13.0/fr/accounting/fiscality/taxes/cash_basis_taxes.html
I would be pleased to have your comments
Best Regards
cc @luceeasypme

**Comment by feketemihai** [comment]
@cvinh The module is for Romania because it only adds a fetch of partners from ANAF regarding the vat on payment, and on the invoices it just do an onchange of the fiscal position for Vat on Payment, for the moment you have to create manually since the PR on Odoo is not merged yet. The rest is done from cash basis because the fiscal position should change normal taxes to the one with cash basis.

In Romania the cash basis is applied for customer invoices based on company, for supplier invoices based on the supplier.

**Comment by cvinh** [comment]
> the PR on Odoo is not merged yet
Could you please point me to that PR ?

**Comment by feketemihai** [comment]
@cvinh https://github.com/odoo/odoo/pulls?q=is%3Apr+is%3Aopen+l10n_ro one is for 13,the other for master.

**Comment by cvinh** [comment]
Thanks

**Pull request merged**
