### PR TITLE
16.0 mig l10n ro partner unique

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
@sbidoul Can i have your help in here with the test-requirements file, as i read from 15 we don;t need to specify the version as odoo16-addon-xxxx, but is not working or i missed something ... can you help or guide what is missing?

**Comment by sbidoul** [comment]
Hi @feketemihai Looks like you found the way in the last commit?

**Comment by sbidoul** [comment]
The failing "Detect unreleased dependencies" is normal, it's to prevent merging with dependencies as git references.

**Comment by feketemihai** [comment]
@sbidoul Only with last one it worked..strange: odoo-addon-l10n_ro_config, before i remember it was as odoo-addon-l10n-ro-config

**Comment by feketemihai** [comment]
> The failing "Detect unreleased dependencies" is normal, it's to prevent merging with dependencies as git references.

Thanks for the quick reaction.

**Comment by sbidoul** [comment]
It's `odoo-addon-` singular. Underscore vs dash doest not matter.

We dropped the Odoo series from the package name to avoid proliferation of OCA projects on PyPI (we have ~11 thousand already :). We can do that now that the pip resolver is smart enough.

**Pull request merged**
